services:
  apiwatch:
    image: theisaac/api-watch:latest
    ports:
      - "22222:22222"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

