services:
  apiwatch:
    build: .
    ports:
      - "${API_WATCH_DASHBOARD_PORT}:${API_WATCH_DASHBOARD_PORT}"
    restart: unless-stopped
    network_mode: host
    env_file:
      - ./.env
    command: python -m apiwatch
