services:
  apiwatch:
    image: theisaac/api-watch:latest
    restart: unless-stopped
    ports:
      - "22222:22222"
    environment:
      - WATCHDOG_USERNAME=${WATCHDOG_USERNAME}
      - WATCHDOG_PASSWORD=${WATCHDOG_PASSWORD}
    volumes:
      - ./apiwatch-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock